services:
  messenger-ingress:
    build:
      context: ./messenger-service/messenger-ingress
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env

  messenger-line-webhook:
    build:
      context: ./messenger-service/messenger-line/webhook
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env

  messenger-line-worker:
    build:
      context: ./messenger-service/messenger-line/worker
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env

  auth-line:
    build:
      context: ./auth-service/auth-line
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env

  auth-twitter:
    build:
      context: ./auth-service/auth-twitter
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env

  messenger-discord-incoming-worker:
    build:
      context: ./messenger-service/messenger-discord/worker/incoming
      dockerfile: Dockerfile
    env_file:
      - ./env/shared.env
      - ./env/local.env
